[package]
name = "canteen-impl"
version = "0.2.5"
authors = ["jeffdn@gmail.com"]

[dependencies]
postgres = { version = "0.11", features = ["chrono"] }
rustc-serialize = "0.3"
chrono = "0.2"
canteen = "0.2"
